/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfece;

import domain.Student;
import file.Student_File;
import java.awt.Color;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author Melvin
 */
public class Insert_Student extends javax.swing.JFrame {

    File file;
    Student_File studentFile;
    String code = "";
    String career = "";

    public Insert_Student() {
        initComponents();
        this.getContentPane().setBackground(Color.lightGray);
        this.setTitle("Add a new Student");
        setResizable(false);
       btn_NewStudent.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_NewStudent = new javax.swing.JLabel();
        lb_NameNewStudent = new javax.swing.JLabel();
        tf_NameNewStudent = new javax.swing.JTextField();
        lb_CodeNewStudent = new javax.swing.JLabel();
        lb_YearNewStudent = new javax.swing.JLabel();
        lb_CareerNewStudent = new javax.swing.JLabel();
        tf_YearNewStudent = new javax.swing.JTextField();
        btn_NewStudent = new javax.swing.JButton();
        cb_CareerNewStudent = new javax.swing.JComboBox<>();
        lbl_CreateCode = new javax.swing.JLabel();
        btn_CreateCode = new javax.swing.JButton();
        lb_Message = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_NewStudent.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        lb_NewStudent.setForeground(new java.awt.Color(255, 255, 255));
        lb_NewStudent.setText("Add a new Student");
        getContentPane().add(lb_NewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 29, 297, -1));

        lb_NameNewStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_NameNewStudent.setForeground(new java.awt.Color(255, 255, 255));
        lb_NameNewStudent.setText("Name");
        getContentPane().add(lb_NameNewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 107, -1, -1));

        tf_NameNewStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(tf_NameNewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 147, 191, 33));

        lb_CodeNewStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_CodeNewStudent.setForeground(new java.awt.Color(255, 255, 255));
        lb_CodeNewStudent.setText("Code");
        getContentPane().add(lb_CodeNewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 525, -1, -1));

        lb_YearNewStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_YearNewStudent.setForeground(new java.awt.Color(255, 255, 255));
        lb_YearNewStudent.setText("Year");
        getContentPane().add(lb_YearNewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 220, -1, -1));

        lb_CareerNewStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_CareerNewStudent.setForeground(new java.awt.Color(255, 255, 255));
        lb_CareerNewStudent.setText("Career");
        getContentPane().add(lb_CareerNewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 363, -1, -1));

        tf_YearNewStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf_YearNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_YearNewStudentActionPerformed(evt);
            }
        });
        getContentPane().add(tf_YearNewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 273, 191, 32));

        btn_NewStudent.setBackground(new java.awt.Color(0, 51, 51));
        btn_NewStudent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_NewStudent.setForeground(new java.awt.Color(255, 255, 255));
        btn_NewStudent.setText("Insert");
        btn_NewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewStudentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_NewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 644, 214, 49));

        cb_CareerNewStudent.setBackground(new java.awt.Color(0, 51, 51));
        cb_CareerNewStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb_CareerNewStudent.setForeground(new java.awt.Color(204, 0, 0));
        cb_CareerNewStudent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Career", "Agronomy", "Computing", "Education" }));
        cb_CareerNewStudent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_CareerNewStudentItemStateChanged(evt);
            }
        });
        cb_CareerNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CareerNewStudentActionPerformed(evt);
            }
        });
        getContentPane().add(cb_CareerNewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 437, 170, 32));

        lbl_CreateCode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_CreateCode.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_CreateCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 578, 96, 29));

        btn_CreateCode.setBackground(new java.awt.Color(0, 51, 51));
        btn_CreateCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_CreateCode.setForeground(new java.awt.Color(255, 255, 255));
        btn_CreateCode.setText("Create Code");
        btn_CreateCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CreateCodeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_CreateCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 518, 214, 38));

        lb_Message.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_Message.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lb_Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 704, 415, 32));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/IMG_512577.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 730, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_CareerNewStudentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_CareerNewStudentItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_CareerNewStudentItemStateChanged

    private void cb_CareerNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CareerNewStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_CareerNewStudentActionPerformed

    private void btn_CreateCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CreateCodeActionPerformed

        file = new File("Students.dat");

        try {
            // Student_File studentFile = new Student_File(file);
            Student_File studentFile = new Student_File(file);
            career = (String) cb_CareerNewStudent.getSelectedItem();
            if (!career.equalsIgnoreCase("Select a Career")) {
                code = studentFile.createsCode(career, tf_YearNewStudent.getText());
                btn_NewStudent.setEnabled(true);
            }
            lbl_CreateCode.setText(code);
        } catch (IOException ex) {
            
        } catch (StringIndexOutOfBoundsException siob) {
            
        }

    }//GEN-LAST:event_btn_CreateCodeActionPerformed

    private void btn_NewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewStudentActionPerformed

       if(!tf_NameNewStudent.getText().equals("") && !tf_YearNewStudent.getText().equals("") && 
           !"Select a Career".equals(cb_CareerNewStudent.getSelectedItem())){
        file = new File("Students.dat");

        try {
            Student_File studentFile = new Student_File(file);

            if (studentFile.addEndRecord(new Student(tf_NameNewStudent.getText(), code, career, tf_YearNewStudent.getText()) {
            })) {
                lb_Message.setText("The student was added");
            } else {
                lb_Message.setText("Problems when adding the student");
            }
        } catch (IOException ex) {
            lb_Message.setText("02 - Error del file");
        }
        tf_NameNewStudent.setText("");
        tf_YearNewStudent.setText("");
        cb_CareerNewStudent.setSelectedItem("Select a option");
        lbl_CreateCode.setText("");
        } else
            lb_Message.setText("All fields must be filled!");
    }//GEN-LAST:event_btn_NewStudentActionPerformed

    private void tf_YearNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_YearNewStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_YearNewStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert_Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CreateCode;
    private javax.swing.JButton btn_NewStudent;
    private javax.swing.JComboBox<String> cb_CareerNewStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_CareerNewStudent;
    private javax.swing.JLabel lb_CodeNewStudent;
    private javax.swing.JLabel lb_Message;
    private javax.swing.JLabel lb_NameNewStudent;
    private javax.swing.JLabel lb_NewStudent;
    private javax.swing.JLabel lb_YearNewStudent;
    private javax.swing.JLabel lbl_CreateCode;
    private javax.swing.JTextField tf_NameNewStudent;
    private javax.swing.JTextField tf_YearNewStudent;
    // End of variables declaration//GEN-END:variables
}
