/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfece;

import domain.Books;
import domain.Loan;
import domain.Student;
import file.AudioVisual_File;
import file.Books_File;
import file.Date_Methods;
import file.Loan_File;
import file.Student_File;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Melvin
 */
public class Insert_LoanBook extends javax.swing.JFrame {

    Date_Methods dateMethods = new Date_Methods();
    ArrayList<Student> studentArray;
    ArrayList<Books> arrayBook;
    Student_File fileStudent;
    Books_File fileBook;
    AudioVisual_File fileAudiovisual;

    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

    public Insert_LoanBook() {
        initComponents();
        this.getContentPane().setBackground(Color.lightGray);
        this.setTitle("Insert Loan");
        tft_Seek.setVisible(false);
        btn_ChangeStudent.setVisible(false);
        btn_RegisterLoan.setVisible(false);

        lb_selectDateInitial.setVisible(false);
        lb_SelectDateReturn.setVisible(false);
        lbl_DaysReturn.setVisible(false);
        //tfd_SeekForCode.setVisible(false);
        lbl_booksFinded.setVisible(false);
        lbl_namee.setVisible(false);
        lbl_booksFinded.setText("");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_InsertLoan = new javax.swing.JLabel();
        tf_SeekStudentInsertLoan = new javax.swing.JTextField();
        lb_seekStudentInsertLoan = new javax.swing.JLabel();
        btn_seekStudentInsertLoan = new javax.swing.JButton();
        btn_RegisterLoan = new javax.swing.JButton();
        lb_selectDateInitial = new javax.swing.JLabel();
        lb_SelectDateReturn = new javax.swing.JLabel();
        lbl_DaysReturn = new javax.swing.JLabel();
        lb_DateBegin = new javax.swing.JLabel();
        lb_DateReturn = new javax.swing.JLabel();
        btn_ChangeStudent = new javax.swing.JButton();
        lbl_Error = new javax.swing.JLabel();
        tft_Seek = new javax.swing.JTextField();
        lb_nameStudent = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_namee = new javax.swing.JLabel();
        lbl_booksFinded = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_InsertLoan.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        lb_InsertLoan.setForeground(new java.awt.Color(255, 255, 255));
        lb_InsertLoan.setText("Loan Book");
        getContentPane().add(lb_InsertLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 32, 224, -1));

        tf_SeekStudentInsertLoan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(tf_SeekStudentInsertLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 156, 264, 31));

        lb_seekStudentInsertLoan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_seekStudentInsertLoan.setForeground(new java.awt.Color(255, 255, 255));
        lb_seekStudentInsertLoan.setText("Enter the code of the student");
        getContentPane().add(lb_seekStudentInsertLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 103, -1, -1));

        btn_seekStudentInsertLoan.setBackground(new java.awt.Color(0, 51, 51));
        btn_seekStudentInsertLoan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_seekStudentInsertLoan.setForeground(new java.awt.Color(255, 255, 255));
        btn_seekStudentInsertLoan.setText("Verify");
        btn_seekStudentInsertLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seekStudentInsertLoanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_seekStudentInsertLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 205, 138, 37));

        btn_RegisterLoan.setBackground(new java.awt.Color(0, 51, 51));
        btn_RegisterLoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_RegisterLoan.setForeground(new java.awt.Color(255, 255, 255));
        btn_RegisterLoan.setText("Register");
        btn_RegisterLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisterLoanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_RegisterLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, 131, 46));

        lb_selectDateInitial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_selectDateInitial.setForeground(new java.awt.Color(255, 255, 255));
        lb_selectDateInitial.setText("Date of loan");
        getContentPane().add(lb_selectDateInitial, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 391, -1, 46));

        lb_SelectDateReturn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_SelectDateReturn.setForeground(new java.awt.Color(255, 255, 255));
        lb_SelectDateReturn.setText("Date of return");
        getContentPane().add(lb_SelectDateReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 519, -1, -1));

        lbl_DaysReturn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_DaysReturn.setForeground(new java.awt.Color(255, 255, 255));
        lbl_DaysReturn.setText("You have 7 days to return any material");
        getContentPane().add(lbl_DaysReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 295, 34));

        lb_DateBegin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_DateBegin.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lb_DateBegin, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 455, 153, 31));

        lb_DateReturn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_DateReturn.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lb_DateReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 554, 153, 32));

        btn_ChangeStudent.setBackground(new java.awt.Color(0, 51, 51));
        btn_ChangeStudent.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_ChangeStudent.setForeground(new java.awt.Color(255, 255, 255));
        btn_ChangeStudent.setText("Change Student");
        btn_ChangeStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChangeStudentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ChangeStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, 33));

        lbl_Error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Error.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lbl_Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 261, 274, 20));

        tft_Seek.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tft_Seek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tft_SeekActionPerformed(evt);
            }
        });
        tft_Seek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tft_SeekKeyReleased(evt);
            }
        });
        getContentPane().add(tft_Seek, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 420, 166, 32));

        lb_nameStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_nameStudent.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lb_nameStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 295, 28));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Type the name of the Book");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/IMG_512577.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        lbl_namee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_namee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_namee.setText("Nombre del estudiante: ");
        getContentPane().add(lbl_namee, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 304, -1, -1));
        getContentPane().add(lbl_booksFinded, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 580, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btn_seekStudentInsertLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seekStudentInsertLoanActionPerformed

        File file = new File("Students.dat");

        try {
            fileStudent = new Student_File(file);

            studentArray = fileStudent.getAllStudents();

            //Recorre el archivo de estudiantes
            for (int i = 0; i < studentArray.size(); i++) {

                //Verifica que el Carnet ingresado sea el de un estudiante registrado
                if (tf_SeekStudentInsertLoan.getText().equalsIgnoreCase(studentArray.get(i).getCode())) {

                    lbl_Error.setText("");
                    lbl_booksFinded.setVisible(true);
                    btn_ChangeStudent.setVisible(true);
                    btn_RegisterLoan.setVisible(true);

                    lb_selectDateInitial.setVisible(true);
                    lb_SelectDateReturn.setVisible(true);
                    lbl_DaysReturn.setVisible(true);
                    tft_Seek.setVisible(true);
                    lbl_namee.setVisible(true);
                    lb_nameStudent.setText(studentArray.get(i).getName());

                    Date actualDate = new Date();
                    lb_DateBegin.setText(sdf.format(actualDate));

                    Date returnDate = dateMethods.sumDays(actualDate, 7);
                    lb_DateReturn.setText(sdf.format(returnDate));

                    tf_SeekStudentInsertLoan.setEnabled(false);
                    btn_seekStudentInsertLoan.setEnabled(false);
                    break;
                } else {

                    lbl_Error.setText("Unregistered student");
                }

            }

        } catch (IOException ex) {
            lbl_Error.setText("Error reading the file");
        }


    }//GEN-LAST:event_btn_seekStudentInsertLoanActionPerformed

    private void btn_RegisterLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisterLoanActionPerformed
        File file = new File("Loans.dat");
        try {
            Loan_File fileLoan = new Loan_File(file);
            Loan newLoan = new Loan(tf_SeekStudentInsertLoan.getText(), tft_Seek.getText(), fileLoan.getFileSize() + "",
                    lb_DateBegin.getText(), lb_DateReturn.getText(), "Pending", 0);
            fileLoan.addEndRecord(newLoan);
        } catch (IOException ex) {
            lbl_Error.setText("Error reading the file.");
        }


    }//GEN-LAST:event_btn_RegisterLoanActionPerformed

    private void btn_ChangeStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChangeStudentActionPerformed

        btn_ChangeStudent.setVisible(false);
        btn_RegisterLoan.setVisible(false);

        lb_selectDateInitial.setVisible(false);
        lb_SelectDateReturn.setVisible(false);
        lbl_DaysReturn.setVisible(false);
        // tfd_SeekForCode.setVisible(false);
        lbl_booksFinded.setVisible(false);
        lbl_namee.setVisible(false);
        tft_Seek.setVisible(false);

        tf_SeekStudentInsertLoan.setEnabled(true);
        tf_SeekStudentInsertLoan.setText("");
        lb_nameStudent.setText("");
        btn_seekStudentInsertLoan.setEnabled(true);

        lb_DateBegin.setText("");
        lb_DateReturn.setText("");
    }//GEN-LAST:event_btn_ChangeStudentActionPerformed

    private void tft_SeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tft_SeekActionPerformed

    }//GEN-LAST:event_tft_SeekActionPerformed

    private void tft_SeekKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tft_SeekKeyReleased
        try {
            fileBook = new Books_File();
            arrayBook = fileBook.getArrayBooks();
            String informationBooks = "";
            for (int i = 0; i < arrayBook.size(); i++) {
                if (fileBook.starsWith(arrayBook.get(i).getName(), tft_Seek.getText())) {
                    informationBooks += arrayBook.get(i).toString();
                    informationBooks += "\n";
                }

            }

            lbl_booksFinded.setText(informationBooks);

        } catch (FileNotFoundException ex) {
            lbl_Error.setText("Error reading books file!");
        }
    }//GEN-LAST:event_tft_SeekKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert_LoanBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert_LoanBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert_LoanBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert_LoanBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert_LoanBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ChangeStudent;
    private javax.swing.JButton btn_RegisterLoan;
    private javax.swing.JButton btn_seekStudentInsertLoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb_DateBegin;
    private javax.swing.JLabel lb_DateReturn;
    private javax.swing.JLabel lb_InsertLoan;
    private javax.swing.JLabel lb_SelectDateReturn;
    private javax.swing.JLabel lb_nameStudent;
    private javax.swing.JLabel lb_seekStudentInsertLoan;
    private javax.swing.JLabel lb_selectDateInitial;
    private javax.swing.JLabel lbl_DaysReturn;
    private javax.swing.JLabel lbl_Error;
    private javax.swing.JLabel lbl_booksFinded;
    private javax.swing.JLabel lbl_namee;
    private javax.swing.JTextField tf_SeekStudentInsertLoan;
    private javax.swing.JTextField tft_Seek;
    // End of variables declaration//GEN-END:variables
}
