/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfece;

import domain.Books;
import file.Books_File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Table_Books extends javax.swing.JFrame {

    Books_File filebook;
    ArrayList<Books> bookArray;

    /**
     * Creates new form Table_Books
     */
    public Table_Books() {
        initComponents();
        matrizBook();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Books = new javax.swing.JTable();
        lbl_Screen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Report of Books");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 23, 280, -1));

        Table_Books = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        Table_Books.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Table_Books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Code", "Year", "Author", "Editorial", "Shape"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Books.setRowHeight(30);
        Table_Books.getTableHeader().setResizingAllowed(false);
        Table_Books.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Table_Books);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 86, 840, 300));

        lbl_Screen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/IMG_512577.jpg"))); // NOI18N
        getContentPane().add(lbl_Screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 880, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void matrizBook() {

        filebook = new Books_File();
        // bookArray = new ArrayList<Books>();

        try {
            bookArray = filebook.getArrayBooks();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Table_Books.class.getName()).log(Level.SEVERE, null, ex);
        }

        String matriz_Book[][] = new String[bookArray.size()][6];

        for (int i = 0; i < bookArray.size(); i++) {

            matriz_Book[i][0] = bookArray.get(i).getName();
            matriz_Book[i][1] = bookArray.get(i).getCode();
            matriz_Book[i][2] = bookArray.get(i).getYear();
            matriz_Book[i][3] = bookArray.get(i).getAuthor();
            matriz_Book[i][4] = bookArray.get(i).getEditorial();
            matriz_Book[i][5] = bookArray.get(i).getType();

        }

        //Temporal para ordenar arreglo tipo burbuja
        String temp = "";
        //Ordena la matriz de BOOKS
        for (int i = 0; i < matriz_Book.length; i++) {
            for (int j = i + 1; j < matriz_Book.length; j++) {
                if (matriz_Book[i][0].compareToIgnoreCase(matriz_Book[j][0]) > 0) {
                    System.out.println(matriz_Book[i][0] + " - " + matriz_Book[j][0]);
                    for (int k = 0; k < matriz_Book[0].length; k++) {
                        temp = matriz_Book[j][k];
                        matriz_Book[j][k] = matriz_Book[i][k];
                        matriz_Book[i][k] = temp;
                    }
                }
            }
        }

        Table_Books.setModel(new javax.swing.table.DefaultTableModel(
                matriz_Book,
                new String[]{
                    "Name", "Code", "Year", "Author", "Editorial", "Shape"
                }
        ));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table_Books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Books;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Screen;
    // End of variables declaration//GEN-END:variables
}
