/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfece;

import domain.Student;
import file.Student_File;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Melvin
 */
public class Table_StudentComputing extends javax.swing.JFrame {

    Student_File fileStudent;
    ArrayList<Student> arrayStudent;
    ArrayList<Student> arrayStudentComputing;

    /**
     * Creates new form Table_Student
     */
    public Table_StudentComputing() throws IOException {
        initComponents();
        matrizStudent();
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_TableStudent = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Student = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_TableStudent.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        lb_TableStudent.setForeground(new java.awt.Color(255, 255, 255));
        lb_TableStudent.setText("Report of Student of Computing");
        getContentPane().add(lb_TableStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 11, 530, 35));

        Table_Student = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        Table_Student.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Table_Student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Code", "Career", "Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Student.setFocusable(false);
        Table_Student.setRowHeight(30);
        Table_Student.getTableHeader().setResizingAllowed(false);
        Table_Student.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Table_Student);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 992, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/IMG_512577.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void matrizStudent() throws IOException {

        File file = new File("Students.dat");

        try {
            fileStudent = new Student_File(file);

            arrayStudent = fileStudent.getAllStudents();

            arrayStudentComputing = fileStudent.getComputingStudents(arrayStudent);

            //  arrayStudentComputing.s
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Table_Books.class.getName()).log(Level.SEVERE, null, ex);
        }

        String matriz_Student[][] = new String[arrayStudentComputing.size()][4];

        for (int i = 0; i < arrayStudentComputing.size(); i++) {

            matriz_Student[i][0] = arrayStudentComputing.get(i).getName();
            matriz_Student[i][1] = arrayStudentComputing.get(i).getCode();
            matriz_Student[i][3] = arrayStudentComputing.get(i).getCareer();
            matriz_Student[i][2] = arrayStudentComputing.get(i).getYear();
            ;

        }

        String temp = "";
        //Ordena la matriz de BOOKS
        for (int i = 0; i < matriz_Student.length; i++) {
            for (int j = i + 1; j < matriz_Student.length; j++) {
                if (matriz_Student[i][0].compareToIgnoreCase(matriz_Student[j][0]) > 0) {
                    System.out.println(matriz_Student[i][0] + " - " + matriz_Student[j][0]);
                    for (int k = 0; k < matriz_Student[0].length; k++) {
                        temp = matriz_Student[j][k];
                        matriz_Student[j][k] = matriz_Student[i][k];
                        matriz_Student[i][k] = temp;
                    }
                }
            }
        }

        Table_Student.setModel(new javax.swing.table.DefaultTableModel(
                matriz_Student,
                new String[]{
                    "Name", "Code", "Career", "Year"
                }
        ));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table_StudentComputing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table_StudentComputing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table_StudentComputing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table_StudentComputing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Table_StudentComputing().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Table_StudentComputing.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Student;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_TableStudent;
    // End of variables declaration//GEN-END:variables
}
